### ISSUE TITLE
Move to nuxt-community?

### ISSUE THREAD

**Issue by ricardogobbosouza** [nuxt-community/robots-module#15]
@WilliamDASILVA How about move this repository to nuxt-community?

**Comment by WilliamDASILVA** [comment]
@ricardogobbosouza 

I don't see any issues with that. Should probably ask to a Nuxt community admin if they are okay with that. If you can do it, go ahead 😄  
Publishing this module in the https://github.com/nuxt-community/awesome-nuxt list would be good start.

**Comment by ricardogobbosouza** [comment]
@WilliamDASILVA 

It's not a issue. I can create and publish repository there.
I just created the repository, later I'll migrate it with your permission, obviously
https://github.com/nuxt-community/robots-module

**Comment by WilliamDASILVA** [comment]
@ricardogobbosouza Couldn't we just transfer the ownership of the module to the `nuxt-community` organization instead of recreating it?

**Comment by ricardogobbosouza** [comment]
@WilliamDASILVA We can, however, not have permission in your repository to transfer

**Comment by WilliamDASILVA** [comment]
@ricardogobbosouza Delete your fork then I can give you the ownership 🙂

**Comment by ricardogobbosouza** [comment]
@WilliamDASILVA  Deleted

**Comment by WilliamDASILVA** [comment]
@ricardogobbosouza Transfered
