### ISSUE TITLE
Add sitemap to robot.txt

### ISSUE THREAD

**Issue by iwatakeshi** [nuxt-community/robots-module#30]
Hi, 

I see a reference to the sitemap [in the source code](https://github.com/nuxt-community/robots-module/blob/master/lib/module.js#L79), but the docs doesn't show how to use it.

I've tried something like the following and it doesn't seem to work.
```js
{
  robots: {
    sitemap: '...'
  }
}
```
Any clue?

Thanks

**Comment by ricardogobbosouza** [comment]
Hi @iwatakeshi, try with `Sitemap`
```js

**Comment by ricardogobbosouza** [comment]
@iwatakeshi 
I'll fix it to identify with sensitive case

**Comment by ricardogobbosouza** [comment]
@iwatakeshi 
fixed case sensitive on `v2.4.1`

**Comment by CavalcanteLeo** [comment]
add on documentation
