### ISSUE TITLE
Disallow is always first

### ISSUE THREAD

**Issue by tsolrm** [nuxt-community/robots-module#32]
It seems like I am unable to change the order of Allow/Disallow in the robots file.. this is a problem when you only want to allow certain pages and disallow the rest as the order matters.

**Comment by ricardogobbosouza** [comment]
Hi @tsolrm 
You can pass array https://github.com/nuxt-community/robots-module#array
So you group and sort as you see fit.

**Comment by TitanFighter** [comment]
Example:

```
['@nuxtjs/robots', [
  { UserAgent: '*' },
  { Allow: ['/*?*page=', '/*.js', '/*.css'] },
  { Disallow: ['/somePage', '/*?*'] }
]]
```
