### ISSUE TITLE
Is the function option will be execute to each call of /robots.txt?

### ISSUE THREAD

**Issue by everyx** [nuxt-community/robots-module#37]
Hi, 

I want to use this module to offer dynamic robots.txt from our API, so can we use it to dynamic generate robots.txt from API in nuxt "universal" mode?

**Comment by ricardogobbosouza** [comment]
Hi @everyx 
In universal mode it will be called on every request.

**Comment by everyx** [comment]
> Hi @everyx
> In universal mode it will be called on every request.

@ricardogobbosouza thanks, so It also have a route cache, can i set the TTL?

**Comment by ricardogobbosouza** [comment]
Yes, you can
