### ISSUE TITLE
Setting options for index & follow

### ISSUE THREAD

**Issue by AdamBD** [nuxt-community/robots-module#38]
Hello,

I want to generate a simple robots.txt with the `index` and `follow` lines listed.

From reading the module its not clear which options property type is correct or what are the differences in execution of you choose either: object, array or function. How are they used differently?

Also under the available options I see listed it doesnt note either index or follow.

Does someone have an example of the best way to set this up?

**Comment by ricardogobbosouza** [comment]
Hi @AdamBD 
I don't know if I understood your question about `index` and `follow`.
About using `object`, `array`, `function` depends on your use case.
