### ISSUE TITLE
how to dynamic set sitemap in robots.txt 

### ISSUE THREAD

**Issue by Cappuuuu** [nuxt-community/robots-module#44]
in front-end, I can get window.location.origin like this screenshot
<img width="297" alt="截圖 2021-03-31 上午11 10 31" src="https://user-images.githubusercontent.com/45985141/113085062-be50d580-9211-11eb-8836-12bc7f16e6e2.png">

but i want set dynamic sitemap in nuxt.config.js  in robots.txt
 ex: `robots: {
    UserAgent: '*',
    Sitemap: ${window.location.origin}/sitemap.xml
  }`, 
here window object is not exist , Is there any good way to resolve it ?  Thanks !

**Comment by Tymo93** [comment]
why don't you use dotenv? you can set a variable to be your origin.

**Comment by fazaio** [comment]
you can use [publicRuntimeConfig](https://nuxtjs.org/docs/2.x/directory-structure/nuxt-config), then use $config to get the value, its available in both server and clien.

 nuxt.config.js
>publicRuntimeConfig: {
    baseURL: 'http://localhost:4000'
  },

get value
> $config.baseURL

**Comment by TitanFighter** [comment]
```
modules: [
    ...
    ['@nuxtjs/robots', {
      UserAgent: '*',
      Sitemap: (req) => `https://${req.headers.host}/sitemap.xml`
    }],
    ...
]
```

**Comment by danielgroen** [comment]
> ```
> modules: [
>     ...
>     ['@nuxtjs/robots', {
>       UserAgent: '*',
>       Sitemap: (req) => `https://${req.headers.host}/sitemap.xml`
>     }],
>     ...
> ]
> ```

Did the trick for me! Would be nice to add tihis up in the README.md since now it is kinda a hidden feature

**Comment by IsraelOrtuno** [comment]
> ```
> modules: [
>     ...
>     ['@nuxtjs/robots', {
>       UserAgent: '*',
>       Sitemap: (req) => `https://${req.headers.host}/sitemap.xml`
>     }],
>     ...
> ]
> ```

Be aware that this would not work on `target: 'static'` mode

**Comment by mklueh** [comment]
@IsraelOrtuno could you please explain **why** it is not working for static mode?

**Comment by IsraelOrtuno** [comment]
@mklueh Static generated sites won't be running any logic in the server side (there's also no server at all) and in this case, the sitemap URL is being generated by a function which will also require access the request headers. For that case it's better to use a ENV variable as @Tymo93 mentioned.

**Comment by mklueh** [comment]
@IsraelOrtuno I see, but isn't there just a hook that gives you all the pages generated after the build is completed? Because I guess Nuxt knows what pages were touched anyway

**Comment by IsraelOrtuno** [comment]
Not sure about the hook but robots.txt serves for more purposes than adding the sitemap URL (which will likely be generated by your own app or a third party module). The point here is that if you pretend to have a dynamic sitemap URL (or any other property in your robots file), it has to run on SSR as that function needs to be executed, otherwise you can make it static with an ENV var.
