### ISSUE TITLE
when is nuxt3 support planned ?

### ISSUE THREAD

**Issue by andysay** [nuxt-community/robots-module#49]
thanks for answer

**Comment by HelloAlexPan** [comment]
bump, has there been any updaters here? Our company is starting a fresh project on Nuxt 3 and have the capacity to help work on a Nuxt 3 build if there are any tasks that need to be completed

**Comment by alijmlzd** [comment]
Same question.

**Comment by dargmuesli** [comment]
@ricardogobbosouza I'd apply as maintainer too, any chance to help out?

**Comment by ricardogobbosouza** [comment]
Start support for nuxt 3/nuxt bridge #52

**Comment by kstraszewski** [comment]
Hi, when is the possible release planned?

**Comment by dargmuesli** [comment]
💚 thank you, @ricardogobbosouza!
