### ISSUE TITLE
Is there any way to make the robots.txt dynamic?

### ISSUE THREAD

**Issue by julifredes** [nuxt-community/robots-module#60]
From the nuxt.config.js file I get the robots dynamically consuming them from our backend.
The problem that we have detected is that the robots are indeed generated with the deployment, but when doing an update of this data on the backend side, they are not reflected in robots.txt.
Among the conclusions we have drawn, we know that the robots are generated when the project is compiled, making it really is not dynamic to obtain this data and forces us to deploy the project to be updated. Is this correct?
What suggestion or recommendation would you give us to solve the generation of robots dynamically obtaining the information from the backend?

**Comment by dargmuesli** [comment]
Was this question posted before or after the v3 prerelease? https://github.com/nuxt-community/robots-module#robots-config should give an answer.

**Comment by julifredes** [comment]
> Was this question posted before or after the v3 prerelease? https://github.com/nuxt-community/robots-module#robots-config should give an answer.

Before the v3 prerelease

**Comment by dargmuesli** [comment]
If v3 works for you, you might want to close this issue.
