### ISSUE TITLE
robots.txt 404 error

### ISSUE THREAD

**Issue by aswinghosh-2hats** [nuxt-community/robots-module#66]
I can access robots.txt in local environment but gives 404 error in server (vercel)

"devDependencies": {
    -------------------
    "@nuxtjs/robots": "^2.5.0",
    "nuxt": "^2.15.8",
}

**Comment by domabbott92** [comment]
Same issue for me.

Works when running `npm run dev`  and `npm run build | npm run start` locally, but neither work on the server. Also tested in development/production mode and, again, both work locally.

Server is nginx
` "@nuxtjs/robots": "^2.5.0",
"nuxt": "2.15.8",`

**Comment by dargmuesli** [comment]
Just to clarify, you are not using bridge?

**Comment by ThomasBerneSV** [comment]
If he was using nuxt bridge, he would be using nuxt-edge and not nuxt library. He is using nuxt 2 without the bridge.
![image](https://user-images.githubusercontent.com/99391157/194231336-131bd4c8-ae14-4c10-9caa-8c22e7b949d0.png)
