### ISSUE TITLE
defineHandler on Nuxt 3 RC12

### ISSUE THREAD

**Issue by g0shed** [nuxt-community/robots-module#69]
RC12 breaks the module

when starting nuxt, this message shows:

import { eventHandler, setHeaders, sendRedirect, defineEventHandler, handleCacheHeaders, createEvent, getRequestHeader, defineHandler, createApp, createRouter as createRouter$1, lazyEventHandler, toNodeListener, readBody, sendError, createError, getQuery, writeEarlyHints } from 'node_modules/h3/dist/index.mjs';
  ^^^^^^^^^^^^^
  SyntaxError: The requested module 'node_modules/h3/dist/index.mjs' does not provide an export named 'defineHandler'

this is due to the breaking changes in H3 and Nuxt

**Comment by tschortsch** [comment]
@ricardogobbosouza would it be possible to create a new release with this bugfix so that we can upgrade our setup to Nuxt RC12?

**Comment by ricardogobbosouza** [comment]
Released [v3.0.0-2](https://github.com/nuxt-community/robots-module/releases/tag/v3.0.0-2)
