### ISSUE TITLE
using nuxt generate on nuxt3 doesnt make robots.txt

### ISSUE THREAD

**Issue by jpengelbrecht** [nuxt-community/robots-module#71]
please see stackblitz,  i can also replicate it locally with nuxt3 RC 11 starter
https://stackblitz.com/edit/github-akyakx?file=package.json,nuxt.config.ts

how to replicate

- run npm run generate
- try find robots.txt file

**Comment by damevin** [comment]
Same for me.. :'(

**Comment by damevin** [comment]
I see your problem, in your stackblitz, you use `"@nuxtjs/robots": "2.0.0"` but for Nuxt3 you need to update `nuxtjs/robots` to v3.0.0.

You can easily do it with 
```
npm update @nuxtjs/robots@3.0.0
———
yarn upgrade @nuxtjs/robots@3.0.0
```

**Comment by ricardogobbosouza** [comment]
Hi @jpengelbrecht 
Use `@nuxtjs/robots@3.0.0-1` with nuxt 3
