### ISSUE TITLE
fix: route is prerendered even for ssr build

### ISSUE THREAD

**Issue by dargmuesli** [nuxt-community/robots-module#76]
Currently a built nuxt page using this module has its `robots.txt` prerendered. That means that e.g. a `Sitemap: (req) => ...req.headers.host...` function has its host set to `localhost` at build time and does not allow dynamic content at deployment.

In PR #75 I changed that behavior to only prerender the route for `target: static`. I added tests to ensure no unwanted regressions.

**Comment by slavco86** [comment]
👍 
Bumping the issue - facing this problem as well. Running SSR Nuxt 3 and build command prerenders robots.txt, resulting in in correct Sitemap behaviour

**Comment by dargmuesli** [comment]
Just add a :+1: to the first post to show your support! :clap:
