### ISSUE TITLE
Not working with Nuxt 2.14.6

### ISSUE THREAD

**Issue by aliaksandr-lindarenka** [nuxt-community/robots-module#85]
Everything worked fine with @nuxtjs/robots 2.5.0, but stoped working on 3.0.0 version. 
I get 404 error, when trying to get robots.txt.

**Comment by ricardogobbosouza** [comment]
Hi @aliaksandr-lindarenka 
To use @nuxtjs/robots v3 with nuxt2 you must install nuxt-bridge
https://nuxt.com/docs/bridge/overview
